name: Go vulnerability checking
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: check for go vulnerabilities
      uses: kmulvey/govulncheck-action@v0.4.0
